baseURL = "http://leeabner.com/"
languageCode = "en-us"
title = "Lee Abner's Blog"
theme = "lanyon"

[params]
  Title = "Lee Abner's Blog"
  Tagline = "A journey of growth and learning in the techology field, with an emphasis on virtualization, cloud, and security"
